// <auto-generated />
using System;
using KPIBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KPIBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408211017_EliminacionAtributoIdObjetivoDeComentario")]
    partial class EliminacionAtributoIdObjetivoDeComentario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KPIBackend.Models.Actividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("ActividadCumplida")
                        .HasColumnType("bit");

                    b.Property<decimal>("CantidadLograda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComentarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescripcionActividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EstrategiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("FechaCumplimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("CreadorId");

                    b.HasIndex("EstrategiaId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("actividades");
                });

            modelBuilder.Entity("KPIBackend.Models.ArchivoPoliticas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("FacultadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultadId");

                    b.ToTable("archivoPoliticas");
                });

            modelBuilder.Entity("KPIBackend.Models.Carrera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("FacultadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCarrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultadId");

                    b.ToTable("carreras");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d488"),
                            FacultadId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d476"),
                            NombreCarrera = "Ingeniería de Software y Sistemas Computacionales."
                        });
                });

            modelBuilder.Entity("KPIBackend.Models.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaComentario")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoObjetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.ToTable("comentarios");
                });

            modelBuilder.Entity("KPIBackend.Models.Directriz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("ComentarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("CreadorId");

                    b.HasIndex("FacultadId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("directrices");
                });

            modelBuilder.Entity("KPIBackend.Models.Estrategia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComentarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescripcionEstrategia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IndicadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("CreadorId");

                    b.HasIndex("IndicadorId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("estrategias");
                });

            modelBuilder.Entity("KPIBackend.Models.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("IndicadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndicadorId");

                    b.ToTable("evidencias");
                });

            modelBuilder.Entity("KPIBackend.Models.Facultad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mision")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slogan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("facultades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d476"),
                            FechaEmision = new DateTime(2026, 3, 17, 6, 0, 0, 0, DateTimeKind.Utc),
                            Mision = "Buscar la mejora tecnológica.",
                            Nombre = "Facultad de Tecnología",
                            Slogan = "Un mundo mejor con tecnología.",
                            Vision = "En 2030, ser una facultad lider en avances tecnológicos."
                        });
                });

            modelBuilder.Entity("KPIBackend.Models.GrupoIndicadores", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DescripcionGrupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroGrupo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("grupo_indicadores");
                });

            modelBuilder.Entity("KPIBackend.Models.Indicador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AccionCorrectiva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CantidadEvidencias")
                        .HasColumnType("int");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescripcionIndicador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DirectrizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Estandar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("FechaCumplimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrecuenciaControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IndicadorCompletado")
                        .HasColumnType("bit");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResponsableAccionCorrectivaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("CreadorId");

                    b.HasIndex("DirectrizId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("ResponsableAccionCorrectivaId");

                    b.ToTable("indicadores");
                });

            modelBuilder.Entity("KPIBackend.Models.PeriodoEscolar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("FechaFin")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("periodos_escolares");
                });

            modelBuilder.Entity("KPIBackend.Models.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d473"),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d481"),
                            Nombre = "Maestro"
                        });
                });

            modelBuilder.Entity("KPIBackend.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("FacultadId");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d490"),
                            CarreraId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d488"),
                            CorreoInstitucional = "rcc74823@lasallebajio.edu.mx",
                            FacultadId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d476"),
                            NombreUsuario = "Rogelio Ceballos Castillo",
                            RolId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d473"),
                            TipoUsuario = "Administrador"
                        });
                });

            modelBuilder.Entity("KPIBackend.Models.Actividad", b =>
                {
                    b.HasOne("KPIBackend.Models.Carrera", "Carrera")
                        .WithMany("Actividades")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Comentario", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KPIBackend.Models.Usuario", "Creador")
                        .WithMany("ActividadesCreadas")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Estrategia", "Estrategia")
                        .WithMany("Actividades")
                        .HasForeignKey("EstrategiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.PeriodoEscolar", "Periodo")
                        .WithMany("Actividades")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Comentario");

                    b.Navigation("Creador");

                    b.Navigation("Estrategia");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("KPIBackend.Models.ArchivoPoliticas", b =>
                {
                    b.HasOne("KPIBackend.Models.Facultad", "Facultad")
                        .WithMany("ArchivoPoliticas")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("KPIBackend.Models.Carrera", b =>
                {
                    b.HasOne("KPIBackend.Models.Facultad", "Facultad")
                        .WithMany("Carreras")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("KPIBackend.Models.Comentario", b =>
                {
                    b.HasOne("KPIBackend.Models.Usuario", "Creador")
                        .WithMany("Comentarios")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("KPIBackend.Models.Directriz", b =>
                {
                    b.HasOne("KPIBackend.Models.Comentario", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KPIBackend.Models.Usuario", "Creador")
                        .WithMany("DirectricesCreadas")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Facultad", "Facultad")
                        .WithMany("Directrices")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.PeriodoEscolar", "Periodo")
                        .WithMany("Directrices")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comentario");

                    b.Navigation("Creador");

                    b.Navigation("Facultad");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("KPIBackend.Models.Estrategia", b =>
                {
                    b.HasOne("KPIBackend.Models.Carrera", "Carrera")
                        .WithMany("Estrategias")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Comentario", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KPIBackend.Models.Usuario", "Creador")
                        .WithMany("EstrategiasCreadas")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Indicador", "Indicador")
                        .WithMany("Estrategias")
                        .HasForeignKey("IndicadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.PeriodoEscolar", "Periodo")
                        .WithMany("Estrategias")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Comentario");

                    b.Navigation("Creador");

                    b.Navigation("Indicador");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("KPIBackend.Models.Evidencia", b =>
                {
                    b.HasOne("KPIBackend.Models.Indicador", "Indicador")
                        .WithMany("Evidencias")
                        .HasForeignKey("IndicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indicador");
                });

            modelBuilder.Entity("KPIBackend.Models.Indicador", b =>
                {
                    b.HasOne("KPIBackend.Models.Carrera", "Carrera")
                        .WithMany("Indicadores")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Directriz", "Directriz")
                        .WithMany("Indicadores")
                        .HasForeignKey("DirectrizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.GrupoIndicadores", "Grupo")
                        .WithMany("Indicadores")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.PeriodoEscolar", "Periodo")
                        .WithMany("Indicadores")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Usuario", "ResponsableAccionCorrectiva")
                        .WithMany()
                        .HasForeignKey("ResponsableAccionCorrectivaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carrera");

                    b.Navigation("Creador");

                    b.Navigation("Directriz");

                    b.Navigation("Grupo");

                    b.Navigation("Periodo");

                    b.Navigation("ResponsableAccionCorrectiva");
                });

            modelBuilder.Entity("KPIBackend.Models.Usuario", b =>
                {
                    b.HasOne("KPIBackend.Models.Carrera", "Carrera")
                        .WithMany("Usuarios")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Facultad", "Facultad")
                        .WithMany("Usuarios")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIBackend.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Facultad");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("KPIBackend.Models.Carrera", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Estrategias");

                    b.Navigation("Indicadores");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("KPIBackend.Models.Directriz", b =>
                {
                    b.Navigation("Indicadores");
                });

            modelBuilder.Entity("KPIBackend.Models.Estrategia", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("KPIBackend.Models.Facultad", b =>
                {
                    b.Navigation("ArchivoPoliticas");

                    b.Navigation("Carreras");

                    b.Navigation("Directrices");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("KPIBackend.Models.GrupoIndicadores", b =>
                {
                    b.Navigation("Indicadores");
                });

            modelBuilder.Entity("KPIBackend.Models.Indicador", b =>
                {
                    b.Navigation("Estrategias");

                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("KPIBackend.Models.PeriodoEscolar", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Directrices");

                    b.Navigation("Estrategias");

                    b.Navigation("Indicadores");
                });

            modelBuilder.Entity("KPIBackend.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("KPIBackend.Models.Usuario", b =>
                {
                    b.Navigation("ActividadesCreadas");

                    b.Navigation("Comentarios");

                    b.Navigation("DirectricesCreadas");

                    b.Navigation("EstrategiasCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
